diafygi/acme-tiny

acme_tiny.py
Use os.path to join paths in a more platform-neutral fashion
=> Join paths platform-neutrally

acme_tiny.py
From https://docs.python.org/2/howto/regex.html#the-backslash-plague:
> backslashes are not handled in any special way in a string literal prefixed with 'r', so r"\n" is a two-character string containing '\' and 'n', while "\n" is a one-character string containing a newline.
=> use raw regex string

acme_tiny.py
textwrap was already imported, so why not use it? :)
From https://docs.python.org/2/library/textwrap.html#textwrap.dedent:
> This can be used to make triple-quoted strings line up with the left edge of the display, while still presenting them in the source code in indented form.
=> use textwrap.dedent

README.md
The current example makes it too easy to shoot yourself in the foot, by overwriting the cert when there's an error renewing it (by running it too many time for testing, or messing up the setup of the challenge directory).
=> cron example: do not write the certificate if there is an error

acme_tiny.py
CA is now a parameter to `get_cert` and the command line utility. This allows for swapping out the ACME servers (staging/production) all within one script.
=> adding CA parameter to command line utility

README.md
server_name names is not a comma separated list host hostsnames.
=> Fixed nginx example

acme_tiny.py
Running on Python 3.2 (and using acme_tiny as a module), I am getting the following error:
```
Traceback (most recent call last):
[snip]
File "server-scripts/letsencrypt-tiny", line 67, in acme
signed_crt = acme_tiny.get_crt(config['acme']['account-key'], csrfile(name), config['acme']['challenge-dir'])
File "/home/ralf/letsencrypt/acme-tiny/acme_tiny.py", line 35, in get_crt
"e": _b64(binascii.unhexlify(pub_exp)),
TypeError: 'str' does not support the buffer interface
```
I can fix that error with the attached patch.
I then ran `./acme_tiny.py` as well to make sure it still works as a Python 2 script.
=> Fix TypeError: 'str' does not support the buffer interface

README.md
The readme states that you must serve challenge files via HTTP.  However, Let's Encrypt understands redirects from HTTP -> HTTPS just fine.
=> For challenges, redirects from HTTP -> HTTPS are fine too

acme_tiny.py
The output of OpenSSL 1.1.0c, included in Debian Testing adds a
whitespace there. Obtaining a certificate list fails that way, since the
list of domains is empty.
=> Make regular expression accept a whitespace after CN.

acme_tiny.py
My openssl (1.1.0e-1) has extra spaces in the Subject line, causing acme-tiny to fail to recognize the hosts's CN and therefore fails to authorize the domains at Letsencrypt.  This PR should fix this.
=> fix parsing of new (?) openssl output format

acme_tiny.py
A subject only CN entry looks in openssl 1.0.2 and earlier like:
Subject: CN=xxx.domain.tld
The output with 1.1.0+ differs slightly:
Subject: CN = xxx.domain.tld
This is enough to get the script confused and to continue with zero
domains and fail later:
|Parsing account key...
|Parsing CSR...
|Registering account...
|Already registered!
|Signing certificate...
|Traceback (most recent call last):
|  File "/home/letsencrypt/acme-tiny/acme_tiny.py", line 198, in <module>
|    main(sys.argv[1:])
|  File "/home/letsencrypt/acme-tiny/acme_tiny.py", line 194, in main
|    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
|  File "/home/letsencrypt/acme-tiny/acme_tiny.py", line 161, in get_crt
|    raise ValueError("Error signing certificate: {0} …
=> Don't fail on openssl 1.1 output

acme_tiny.py
CN used to be without whitespaces around the `=` but OpenSSL 1.1 introduced
whitespaces:
1.0.1: subject=/CN=example.com
1.1.0: subject=CN = example.com
This commit makes them optional.
=> FIX CN parsing to work with OpenSSL 1.1

acme_tiny.py
Many people simply copy the acme_tiny.py script, meaning they
lose the licensing information that is included in a separate file.
This adds one extra comment line to the top of the file stating
who the copyright owner is, and what license it is under.
=> Include licensing information in acme_tiny.py itself

README.md
Updated Readme to reflect the fact that this script does not need access to the private TLS key.
(also added one space)
=> Readme: Only needs access to private account key

.travis.yml, README.md, acme_tiny.py, setup.py, tests/test_module.py
CHANGELOG
* Support POST-as-GET from updated ACME spec (RFC 8555) - Let's Encrypt will drop support for plain GET requests in November 2019 (issue #226)
* Added explicit Python 3.7 support and fixed continuous integration tests
* Added timeout to request polling to prevent infinitely waiting (pull #205)
* Added support for critical SAN extensions (issue #216, pull #217)
* Started cleaning up challenge files on success (pointed out by @felixfontein in issue #222)
I feel like supporting POST-as-GET, which is a breaking change from Let's Encrypt, warrants a minor version bump.
=> Proposed 4.1.0 release

README.md
We [no longer](https://github.com/openssl/openssl/commit/bfa470a4f64313651a35571883e235d3335054eb) have to use such a messy/kludgy/breakable syntax to add `subjectAltName` entries to a CSR.
This pull request updates the README to recommend the new, officially-supported syntax, while still listing the old workaround for versions of OpenSSL that don't officially support adding `subjectAltName`s inline.
=> Recommend -addext for subjectAltName

README.md, acme_tiny.py
The --dry-run option is a shortcut for
--directory-url https://acme-staging-v02.api.letsencrypt.org/directory
to use Let's Encrypt staging environment for testing.
=> Add --dry-run command line option

README.md
Duplicate intermediate certificates are [known to cause issues with GnuTLS 3.7.0 based clients](https://gitlab.com/gnutls/gnutls/-/issues/1131) on servers not based on GnuTLS (e.g. OpenSSL-based servers). Document this in the according upgrade note in README.md.
=> 4.x upgrade note: Mention issues with GnuTLS 3.7.0

acme_tiny.py
Just a small change to log (or print) the Let’s Encrypt [account ID](https://letsencrypt.org/docs/account-id/).
It is useful to have this information for certain tasks like [opting in](https://community.letsencrypt.org/t/ecdsa-availability-in-production-environment/150679) for ECDSA intermediates.
Feel free to merge if you consider this useful too.
=> Log the Let’s Encrypt account ID

acme_tiny.py
Authorizations that already have a status of "valid" do not need
to be validated again (until the authorization expires).
Skipping these authorizations makes it possible to obtain certificates
for domains for which a dns-01 validation is still valid, as
acme_tiny is unable to re-validate them. (The alternative would be
to wait up to a month until the authorization expires, or use a
different acme client.)
=> skip valid authorizations

acme_tiny.py
From #241, some other ACME CAs (besides Let's Encrypt) require contact info to register an initial account.
This pull request adds contact info (if provided) by default to the initial account registration request.
=> add contact to initial registration request

acme_tiny.py
People over at the DebOps project encountered problems running
acme-tiny on Python 3-only systems [1]. As described in the Debian
Python Policy [2], this behaviour is expected when using the
(discouraged) 'python' interpreter. This commit modifies the shebang
line to specify the 'python3' interpreter instead.
[1] https://github.com/debops/debops/issues/1079#issuecomment-562854976
[2] https://www.debian.org/doc/packaging-manuals/python-policy/python.html#interpreter
=> Set interpreter to 'python3'
